enum purpose {
    CARGO_DELIVERY,
    UNDERGROUND_SCANNING,
    OBJECT_DISCOVERY,
    OBJECT_RECOGNITION,
    OBJECT_FOLLOWING,
    CARTOGRAPHY,
    ENVIRONMENT_3D_SCANNING,
    AREA_SPRAYING,
    AREA_SOWING
}